### ISSUE TITLE
Arms Warrior Ignore Pain and Shield Block.

### ISSUE THREAD

**Issue by DakHarding** [Dicebar/Raven#39]
Hello again, on retail with Arms Warrior, still running into intermittent issues again with cooldowns showing available while still counting down. Sometimes 4-5 seconds out. Specifically Ignore Pain and Shield Block. 

Also, attached a pic and the following Shield Block conditional doesn't seem to work even though all criteria are true. Thanks.
![ShieldBlockBug](https://user-images.githubusercontent.com/118600255/223919971-eda1356d-b457-4c22-8e18-b5b308caf7f3.png)

_Originally posted by @DakHarding in https://github.com/Dicebar/Raven/issues/36#issuecomment-1461274598_

**Comment by Dicebar** [comment]
Thanks, I'll have a look!

**Comment by Dicebar** [comment]
I've created a patch for the bugs that caused these issues.

The Shield Block one was actually caused by the cooldown cache incorrectly overwriting the cooldown of the ability "Shield Block" with the Protection rank-up that gives Shield Block two charges. That passive ability is also called "Shield Block", which obviously has no cooldown to test for and is never a usable ability.

Anyway, a new release should be on its way through the CurseForge pipelines at the moment.
