### ISSUE TITLE
Conditions locking up

### ISSUE THREAD

**Issue by dorana** [Dicebar/Raven#5]
By DakHarding on CF:

> So I reset my Evoker profile and spent the evening yesterday rebuilding all my bars, icons, and conditionals for Evoker Devastation abilities. I'm still running into a slight problem where conditionals cease to function.
> 
> To try and be specific: I have one bar/icon relying on a conditional for "Shattering Star" that only appears when it's off CD and I have an unfriendly target targeted under Target Status. Hides when false. Unhides when true. Pretty standard stuff. When it works, it works great. But then, during a fight/normal rotation (not every time), it will just stop working and the condition value stays "stuck" at False -- even though it's off CD and I have an unfriendly target targeted.
> 
> The only way I've been able to get it working again (now) is by using another ability on my hotbar. In this instance, "Fire Breath" (which is one of the new empowered Evoker abilities that ramps up and requires 2 button taps). Once that fires off, the conditions kick-in again and everything works fine. There doesn't seem to be any real rhyme or reason to it. Sometimes, I can go 30+ minutes without anything failing.
> 
> Over the years of using Raven, I have noticed some funky behavior when playing around with the conditions under 'Target Status'. For instance, the Range conditional has flat out never worked. "If target is in range, then true/false" etc.. It just doesn't operate properly.
> 
> I used to communicate directly with Tomber regarding these types of behaviors. I'm thankful someone has picked-up the reigns with the time and coding knowledge to continue improving Raven. I'm not sure if there's currently plans in the works to add the new Evoker class into Raven with the Essences. Just as there are with chi-points, combo points, soul shards, etc. under the Player Status conditions. But, I look forward to both receiving and providing feedback moving forward to make Raven a terrific addon!
> 
> Thank you!

**Comment by DakHarding** [comment]
[Raven.zip](https://github.com/Dicebar/Raven/files/10046679/Raven.zip)
Hopefully this goes through. I have several accounts that I use Raven with, but the one I'm mainly having issues with (the conditions) is the new Evoker class - my toon named "Purplehãze" - in particular when using a condition for the talented ability 'Shattering Star' under the Devastation tree. Randomly freezes in a 'false' value when all all conditions are actually true. Thanks.

**Comment by DakHarding** [comment]
I can now confirm 100% this is only happening on the new Evoker toon I made. All other toons/classes I play with aren't experiencing any condition freezes. Thanks!

**Comment by Dicebar** [comment]
Sorry it took so long to get back to you. Been a bit overwhelmed at work.

Unfortunately, it appears your profile is corrupted. For various conditions the targeting information was not stored on your profile.

As an example, for the "Shattering Star" condition there is a dependency on the "Disintegrate CHANNELING" condition, but if you look at the summary of that condition you'll notice that where it says "Spell casting: ", there is actually no spell. This is caused by missing check next on the condition for "Who is casting".

You can see the same thing happening for the "Living Flame" condition, where the summary for "Any buffs" is missing a spell name because "Who has buff" has no option selected.

Correcting these kinds of problems will always need some sort of player input, as we can't decide for the player which option should be selected. So the best we could do to help resolve these issues is to make some sort of validation routine that alerts players when conditions are incomplete. However, I suspect (and fervently hope) that this was caused by a bug we've already fixed 🤞

**Comment by DakHarding** [comment]
Quick question: Is it in the code itself where it's not showing because in the addon in-game itself (see attached pics), those areas described are showing correctly on my end.

![Raven Bug Testing 11 26 22 - Disintegrate](https://user-images.githubusercontent.com/118600255/204083299-fc35a0b1-37f8-44df-82e0-e0d8f5c10adb.png)
![Raven Bug Testing 11 26 22 - Living Flame](https://user-images.githubusercontent.com/118600255/204083300-aab2f024-3c15-4e13-ac0a-5a0b42852a06.png)

**Comment by Dicebar** [comment]
Interesting. When I used your profile it didn't show up like that at all, which was an obvious problem.

I'll have to have another look!

**Comment by Dicebar** [comment]
Can you see if the behavior mentioned above appears when your conditions get bugged?

**Comment by DakHarding** [comment]
Sorry, tonight I finally got around to playing my Evoker now that Dragonflight is here. 

Five minutes into fighting on the new isle and it happened. Shattering Star conditional seized up. And of course, it kicks back in when I fire off either Fire Breath or Eternity Surge. In the screenshot, on my hotbar below, you can see Azure Strike (third button from left) is the only thing lit up (with the yellow border) because it thinks Shattering Star, along with everything else, has a false value. But in fact, none of them should be false as they're all off CD and ready to go.

Very strange. No other toon is experiencing this and I have some pretty monster conditionals setup in their profiles.

![Raven Bug Testing 11 29 22 - Shattering Star](https://user-images.githubusercontent.com/118600255/204718180-8c3f2dd8-1ce4-42a7-bb24-44dd89e59687.png)

**Comment by DakHarding** [comment]
Also, here's my current Evoker talent loadout if it helps at all. The new UI allows to just import it in and updates on the fly which is pretty nice:

BsbBnWR3R1Z1HmbUKIpvm3XXhTBBAAAAAAoFkkEQCJQJJJtAASkkAkkEkkkkA

**Comment by Dicebar** [comment]
Thanks for the talent string, that might help. I just made sure I had Shattering Star on my bars for testing purposes, but that may not be enough.

If it also kicks back in, on its own without a reload, that kind of suggests that the condition itself is bugged (read: not Raven, but a "bug" in the configuration of the  condition). In the screenshot, Shattering Star is greyed out on your hotbar. That suggests the condition's result should be false simply based on the action status. What am I missing here?

**Comment by DakHarding** [comment]
Ya know, I never really paid much attention to bartender being sorta faded out like that. It ONLY does that when you're channeling/casting an Empower ability (Fire Breath or Eternity Surge). 

I just did some really quick research and apparently there's a lot of issues regarding these Empowered abilities on the forums and wowhead. AND, I just discovered this new option in the Blizzard UI that allows you to switch from 'Hold and Release' to 'Press and Tap' (see screenshot)? 

I'm going to switch to Press and Tap and see what happens. I'll follow-up after further testing with this new option.

![Raven Bug Testing 11 29 22 - General UI Empowered Spell Input](https://user-images.githubusercontent.com/118600255/204737172-be07c36e-cbaf-4f14-bce4-d3a3868b8d41.png)

**Comment by Dicebar** [comment]
Thanks, it's appreciated! 👍

**Comment by DakHarding** [comment]
Well, it happened again while using Press and Tap. 

For a long while I was cruising right along with no issues, but just now - it froze as if it's stuck in a Empower loop. I'm now 100% certain this is an in-game issue and no fault of Raven so I'll consider this a non-issue on the addon side since there's several others experiencing the same madness on Evoker. Folks have submitted several bugs on the "stuck" issue in the forums. I piggy-backed off someone's bug report here: https://us.forums.blizzard.com/en/wow/t/a-few-evoker-issues-i-have-noticed/1405865

Thanks for your time/energy/attention on trying to figure this out. I'm just going to deal with it the meantime.

**Comment by Dicebar** [comment]
Anytime 🙂

That bug is so weird, but it does explain a lot. I agree that it's a Blizzard thing, and I hope they fix it soon 🤞
