### ISSUE TITLE
[BETA] Temporary Weapon Enchant Blocks Bar Loading on Initial UI Load

### ISSUE THREAD

**Issue by kfred93** [Dicebar/Raven#70]
When a user initially loads the UI on a character with rogue poisons on their weapons, Raven bars will not load. Unlocking the anchors does not affect the display. The weapon that had the enchant did not affect the behavior - any weapon with a poison caused the bars to fail to load. 

Removing the weapon poison and reloading the UI caused the bars to display as expected. Applying weapon poison after the UI initially loads does not affect the behavior of the bars further.

 It is unknown if this affects all weapon enchants, or simply rogue weapon enchants. 
 
 No Lua error is thrown.

**Comment by kfred93** [comment]
Here's a GIF illustrating the behavior. The top set of icons are the normal Blizzard icons. The GIF starts with the bars visible and a poison present. The UI is then reloaded and the bar is no longer visible. The poison is then removed and the UI reloaded again - bar back as expected.

![DyByuDI](https://github.com/Dicebar/Raven/assets/28148008/1ed1508e-fc26-4b47-aafe-3099d35c705b)

This behavior was reconfirmed with all other addons disabled.

**Comment by kfred93** [comment]
Retested on a Shaman with Frostband Weapon - same behavior.

**Comment by Dicebar** [comment]
Hi @kfred93. Thank you for your triple A report, it is very much appreciated.

My apologies for responding so belatedly. I've been ill past few weeks and while I saw your post, I forgot to respond.

During Cata beta there was a bug relating to how Blizzard labeled how new the expansion was, causing problems with how the addon identifies the way to interact with game data. They have since fixed this, and there is a good chance that this was the cause of the problem with how weapon buffs are handled.

As I don't have a character with weapon enchants on WoW Cata, could I ask you to confirm if this is now working properly?

**Comment by kfred93** [comment]
All good! I'm not too sure if the bug is gone - beta is acting up in other ways.

The issue did change last week sometime - now a Lua error is thrown when a weapon enchant is applied to a weapon. The bars also now fail to load as well, even before the error is thrown. Error is attached.

I think this new issue is going to be a blizzard issue as /script C_TooltipInfo.GetInventoryItem("player", 16, false) works on live servers, but throws an identical error as listed below on Beta.

So I'm not sure if the issue is gone from Beta yet, but I'll continue to keep an eye on it!

[lua_error_5_2-24.txt](https://github.com/Dicebar/Raven/files/15185990/lua_error_5_2-24.txt)

**Comment by Dicebar** [comment]
The C_TooltipInfo bug should be resolved as of r653.

Thanks again for the reports 😊
