### ISSUE TITLE
Another issue TWW - r670

### ISSUE THREAD

**Issue by Peregran** [Dicebar/Raven#86]
This was on my Fury warrior, landing and looting seem to be happening

9x bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))
[string "=[C]"]: in function `GetSpellInfo'
[string "@Raven/Shims.lua"]:88: in function `GetSpellInfo'
[string "@Raven/Profile.lua"]:358: in function `SetCooldownDefaults'
[string "@Raven/Profile.lua"]:121: in function `InitializeProfile'
[string "@Raven/Main.lua"]:873: in function <Raven/Main.lua:869>
[string "=[C]"]: ?
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:103: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:96: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:91: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:83: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:79>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))"

**Comment by Dicebar** [comment]
I've got to say this one left me stomped.

Best I can tell, the error suggests that Raven is trying to index the spells of your pet. But as a fury warrior, you don't have a pet and so there are no pet spells to index, causing the error.

Were you in an unusual situation, like sitting in a vehicle or something similar?

I did pushed an update which _might_ do something, but honestly I'm skeptical.

**Comment by Koskun** [comment]
Might they have been doing one of the Hunts and had a pet from that?

**Comment by Dicebar** [comment]
> Might they have been doing one of the Hunts and had a pet from that?

That could be it, maybe.

In `r672` there was a bugfix for hunter pets, I'm hoping that that fix corrects this problem as well.

@Peregran: Can you confirm?

**Comment by zipzip98** [comment]
using r672 right now and having a problem. it's probably because of the same reason, "error happens on non-pet classes". all my characters at lvl70.

Havoc DH - raven doesn't work
Vengeance DH - raven doesn't work
BM Hunter - no problem
Blood DK - no problem
Unholy DK - no problem
Affliction Warlock - no problem

that's the LUA error i'm getting,

Message: bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))
Time: Thu Jul 25 19:13:15 2024
Count: 1
Stack: bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))
[string "@Interface/AddOns/Raven/Shims.lua"]:88: in function `GetSpellInfo'
[string "@Interface/AddOns/Raven/Main.lua"]:1094: in function <Interface/AddOns/Raven/Main.lua:1065>
[string "@Interface/AddOns/Raven/Main.lua"]:1274: in function `Update'
[string "@Interface/AddOns/Raven/Main.lua"]:953: in function <Interface/AddOns/Raven/Main.lua:949>
[string "@Interface/AddOns/Raven/Main.lua"]:984: in function `?'
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/CanIMogIt/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../AddOns/CanIMogIt/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: self = <table> {
}
spellID = nil

**Comment by Dicebar** [comment]
That's nice and specific, and I can actually recreate this bug on my DH as well. Thanks!

**Comment by Dicebar** [comment]
The Demon Hunter problem should be fixed as of `r673`. Can either of you confirm?

Also, @Peregran: An earlier fix for hunters might apply to the problem you ran into with your Fury Warrior. Can you test if your Fury Warrior is still bugged with `r673`?

**Comment by zipzip98** [comment]
@Dicebar,
using r673 now and it seems DH problem has been fixed. checked my DH, DK, Hunter and Warlock characters, everyhing is fine.

I thank you very much for your support.

**Comment by Dicebar** [comment]
Very much welcome, thanks for confirming the fix!
