### ISSUE TITLE
"Show When: Mounted" doesn't count druid travel form

### ISSUE THREAD

**Issue by coachseat** [Dicebar/Raven#95]
Hi there,

Just noticed that druid travel form doesn't hide a bar group that should be hidden when mounted.

Thanks!

**Comment by Dicebar** [comment]
Apologies for the late response, I have been unwell.

I made a fix for TWW, which is included in the `r682` release. The "is mounted" condition now considers ground, aquatic and flying forms as mounts.

I couldn't test this for classic, so I left the behavior unchanged there and it only tests for flight form there.

It looks like this bug was introduced way back in 2018, so good find! Thanks for the report 😊
